# Generated by Django 3.2.12 on 2024-02-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0007_set_cover_null_when_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('number_type', models.CharField(max_length=32)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.CharField(choices=[('cropping required', 'cropping required'), ('blurry photo', 'blurry photo'), ('wrong book', 'wrong book'), ('generic cover', 'generic cover')], max_length=32)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cover.coverimage')),
            ],
        ),
        migrations.AddIndex(
            model_name='badcover',
            index=models.Index(fields=['number_type', 'number'], name='bad_cover'),
        ),
        migrations.AlterUniqueTogether(
            name='badcover',
            unique_together={('number_type', 'number')},
        ),
        migrations.AlterIndexTogether(
            name='badcover',
            index_together={('number_type', 'number')},
        ),
    ]
